---
# This play will only get consumed in osh-images.
# For depends-on to osh-images and osh changes triggering a rebuild of
# osh-infra or osh, this play won't be used, as we won't know what to build, and
# therefore will build everything for a 'standard' distribution.
# No need to change zuul.project.src_dir to static paths then.
- hosts: all[0]
  vars:
    default_environment:
      LOCI_SRC_DIR: "{{ ansible_user_dir }}/src/git.openstack.org/openstack/loci"
  tasks:
    - name: Build image
      shell: "{{ build_command | default('./build.sh') }}"
      args:
        chdir: "{{ zuul.project.src_dir }}/openstack/loci/"
        executable: /bin/bash
      environment: "{{ (build_environment | default({})) | combine(default_environment) }}"
