name: Build OVN-BGP-Agent Image
on:
  workflow_dispatch:
  push:
    paths:
      - 'ovn-bgp-agent/**'

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  NAMESPACE: openstackhelm

jobs:
  build-ovn-bgp-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu_noble, ubuntu_jammy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push ovn-bgp-agent
        run: |
          cd ovn-bgp-agent
          chmod +x build.sh
          
          # 映射 DISTRO 变量
          export DISTRO="${{ matrix.distro }}"
          export PROJECT_REF="master"
          export REGISTRY="${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.NAMESPACE }}"
          export IMAGE_PREFIX=""
          export PUSH="true"
          
          echo "Building ovn-bgp-agent:master-${DISTRO}"
          ./build.sh

      - name: Verify image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.NAMESPACE }}/ovn-bgp-agent:master-${{ matrix.distro }}"
          docker pull ${IMAGE}
          docker inspect ${IMAGE}